const lovePoems = [
    "Roses are red, violets are blue, my love for you is endless and true.💖",
    "In your eyes, I see a universe of love, and in your embrace, I find my solace.💖",
    "Love is the journey of a lifetime, and I want to spend every moment of it with you.💖",
    "Your laughter is the sweetest music, and your love is the most precious gift.💖",
    "Like a gentle breeze, your touch soothes my soul and brings peace to my heart.💖",
    "In your smile, I find the courage to face each day, for it radiates warmth and hope.💖",
    "Your love is the canvas of my life, and together, we paint a masterpiece of passion.💖",
    "With you, every day is Valentine's Day, and every night, a dream of endless love.💖",
    "Your love is my anchor, grounding me in the stormy sea of life's uncertainties.💖",
    "In the tapestry of my life, you are the most beautiful thread, weaving love into my heart.💖",
    "You are the whisper of the wind, the glow of the moon, and the warmth of the sun in my life.💖",
    "I searched for love, and I found it in your eyes; now, I'm forever lost in your gaze.💖",
    "In your arms, I've found my sanctuary, where all worries fade, and love takes its place.💖",
    "Your love is a symphony that fills my heart with sweet melodies.💖",
    "Every moment with you is a treasure, a love story that I want to cherish forever.💖",
    "Your smile lights up the darkest corners of my soul, bringing warmth and joy.💖",
    "In your presence, I've discovered the magic of love, and it's a spell I never want to break.💖",
    "Love is not just a word; it's the feeling I get when I'm with you, so warm and real.💖",
    "With you, the ordinary becomes extraordinary, and life is a beautiful adventure.💖",
    "I fall in love with you every day, as your love is a gift that keeps on giving.💖",
    "You are the answer to all my questions, and in your love, I find my purpose.💖",
    "In your embrace, I've found my home, and in your heart, my eternal love.💖",
    "Our love is a journey with no end, filled with memories and dreams to share.💖",
    "Your love is a guiding star, leading me through life's uncharted territories.💖",
    "When we are apart, I feel incomplete, for you are the missing piece of my soul.💖",
    "Your love is a gentle rain, quenching the thirst of my heart's barren land.💖",
    "Like a river flows to the sea, your love always finds its way to me.💖",
    "In the garden of love, you are the most beautiful, radiant flower.💖",
    "Your love is a symphony that plays in the depths of my heart, sweet and harmonious.💖",
    "When I say 'I love you,' it's not out of habit; I say it to remind you that you are my life.💖",
    "In your eyes, I see a future where we share love, laughter, and endless adventures.💖",
    "Your love is the melody that lulls me to sleep and wakes me with a joyful heart.💖",
    "With you, every day is an opportunity to write a new chapter of our love story.💖",
    "I am yours, and you are mine; together, we create a love that is endlessly divine.💖",
    "Your love is a beacon of hope in the darkest night, guiding me to your warm embrace.💖",
    "In your laughter, I find happiness; in your love, I find my purpose.💖",
    "With you, my heart has found its home, a place where love and dreams intertwine.💖",
    "Your love is the treasure that I seek, and in your eyes, I find the universe I adore.💖",
    "Every day, I fall in love with you all over again, for your love is a beautiful renewal.💖",
    "You are the poetry of my heart, and every word is a testament to our love's art.💖",
    "In the canvas of my life, you are the most vibrant and beautiful stroke of love.💖",
    "With you, I've discovered the true meaning of love, and it's a story I want to keep telling.💖",
    "You are the sunshine that brightens my day, and the moonlight that comforts my night.💖",
    "Your love is the gentle rain that nurtures the garden of our hearts, making it bloom.💖",
    "In your eyes, I find a universe of love 💖",
    "In the melody of your laughter, my heart finds its song 💖",
    "In your smile, I see the morning sun's first ray,In your laughter, I find the joy of a brand new day. 💖",
    "Our love story is written in the stars, and I cherish every chapter as a gift from above.💕",
    "In your smile, I find the courage to face each day, for it radiates warmth and hope.💖",
    "Your love is the canvas of my life, and together, we paint a masterpiece of passion.💖",
    "With you, every day is Valentine's Day, and every night, a dream of endless love.💖",
    "Your love is my anchor, grounding me in the stormy sea of life's uncertainties.💖",
    "In the tapestry of my life, you are the most beautiful thread, weaving love into my heart.💖",
    "You are the whisper of the wind, the glow of the moon, and the warmth of the sun in my life.💖",
    "I searched for love, and I found it in your eyes; now, I'm forever lost in your gaze.💖",
    "In your arms, I've found my sanctuary, where all worries fade, and love takes its place.💖",
    "Your love is a symphony that fills my heart with sweet melodies.💖",
    "Every moment with you is a treasure, a love story that I want to cherish forever.💖",
    "Your smile lights up the darkest corners of my soul, bringing warmth and joy.💖",
    "In your presence, I've discovered the magic of love, and it's a spell I never want to break.💖",
    "Love is not just a word; it's the feeling I get when I'm with you, so warm and real.💖",
    "With you, the ordinary becomes extraordinary, and life is a beautiful adventure.💖",
    "I fall in love with you every day, as your love is a gift that keeps on giving.💖",
    "You are the answer to all my questions, and in your love, I find my purpose.💖",
    "In your embrace, I've found my home, and in your heart, my eternal love.💖",
    "Our love is a journey with no end, filled with memories and dreams to share.💖",
    "Your love is a guiding star, leading me through life's uncharted territories.💖",
    "When we are apart, I feel incomplete, for you are the missing piece of my soul.💖",
    "Your love is a gentle rain, quenching the thirst of my heart's barren land.💖",
    "Like a river flows to the sea, your love always finds its way to me.💖",
    "In the garden of love, you are the most beautiful, radiant flower.💖",
    "Your love is a symphony that plays in the depths of my heart, sweet and harmonious.💖",
    "When I say 'I love you,' it's not out of habit; I say it to remind you that you are my life.💖",
    "In your eyes, I see a future where we share love, laughter, and endless adventures.💖",
    "Your love is the melody that lulls me to sleep and wakes me with a joyful heart.💖",
    "With you, every day is an opportunity to write a new chapter of our love story.💖",
    "I am yours, and you are mine; together, we create a love that is endlessly divine.💖",
    "Your love is a beacon of hope in the darkest night, guiding me to your warm embrace.💖",
    "In your laughter, I find happiness; in your love, I find my purpose.💖",
    "With you, my heart has found its home, a place where love and dreams intertwine.💖",
    "Your love is the treasure that I seek, and in your eyes, I find the universe I adore.💖",
    "Every day, I fall in love with you all over again, for your love is a beautiful renewal.💖",
    "You are the poetry of my heart, and every word is a testament to our love's art.💖",
    "In the canvas of my life, you are the most vibrant and beautiful stroke of love.💖",
    "With you, I've discovered the true meaning of love, and it's a story I want to keep telling.💖",
    "You are the sunshine that brightens my day, and the moonlight that comforts my night.💖",
    "Your love is the gentle rain that nurtures the garden of our hearts, making it bloom.💖",
    "In your eyes, I find a universe of love 💖",
    "In the melody of your laughter, my heart finds its song 💖",
    "In your smile, I see the morning sun's first ray,In your laughter, I find the joy of a brand new day. 💖",
    "Our love story is written in the stars, and I cherish every chapter as a gift from above.💕",
    "In your eyes, I've found a reflection of a love that's boundless, a connection that's timeless.💖",
    "With you, every day is an adventure, a journey of love and laughter, where dreams come true.💖",
    "Your love is the compass that guides my heart through the storms of life, leading me to you.💖",
    "In the warmth of your embrace, I find solace, a shelter from life's chaos, and a haven for my heart.💖",
    "Like a river that flows without end, your love rushes through my soul, a constant, beautiful stream.💖",
    "With you, every moment becomes a memory I cherish, a testament to the love we share.💖",
    "Your laughter is the sweetest melody, and in its notes, I find the music of our love's symphony.💖",
    "In your smile, I see the promise of a brighter day, and the assurance that everything will be okay.💖",
    "Your love is the anchor that keeps me grounded, a steadfast presence in life's changing seas.💖",
    "In the tapestry of our love, you are the most vibrant thread, weaving a story of passion and endless love.💖",
    "With you, every day is a celebration, a chance to dance in the joy of love's sweet elation.💖",
    "Your love is the poetry that dances within my heart, the verses that tell the story of our eternal art.💖",
    "With every sunrise, I'm reminded of your radiant smile, and it warms my heart for miles.💖",
    "In the stillness of the night, I feel your love's sweet embrace, a comfort no one can replace.💖",
    "You are the melody that plays in my heart's song, a love that's steady and strong.💖",
    "With you, every day is a treasure trove of moments, and our love's journey is the ultimate compliment.💖",
    "In your eyes, I find the reflection of our shared dreams, a love story that forever gleams.💖",
    "Your love is the lighthouse guiding me through life's storms, keeping me safe, and my heart warms.💖",
    "Like a river flows gently to the sea, your love's current carries you to me.💖",
    "In the garden of our love, you are the most beautiful rose, and in your presence, my heart glows.💖",
    "With you, my heart is a symphony, a melodious song, a love that's forever strong.💖",
    "Your laughter is the sweetest note in life's grand melody, a source of endless harmony.💖",
    "In your smile, I see the dawn of a new day, a promise of love that's here to stay.💖",
    "Your love is the compass that guides me on life's quest, through every trial, you are the best.💖",
    "With you, every day is a canvas for our love's art, and it paints a masterpiece from the heart.💖",
    "In your embrace, I find the shelter from life's storm, a love that's pure and endlessly warm.💖",
    "Like a star in the night, your love lights my way, and I'm grateful for you every day.💖",
    "With you, every moment is a precious gem, a love that's pure, no need to condemn.💖",
    "Your laughter is the magic that brightens my days, and in your love, my heart sways.💖",
    "In your smile, I see the promise of a love so true, a future together, me and you.💖",
    "Your love is the anchor in life's turbulent sea, holding me steady, setting me free.💖",
    "With you, every day is an adventure, a journey that's boundless, where our love finds rapture.💖",
    "In your eyes, I see a universe, a world of dreams, where love endlessly streams.💖",
    "Your love is the poetry that dances in my soul, a story of us that makes me whole.💖",
    "With you, life is a grand masterpiece, a journey with love that will never cease.💖",
    "Your laughter is the sweetest symphony, a melody of love and endless harmony.💖",
    "In your smile, I find the key to my heart's delight, a love so strong, it feels just right.💖",
    "Your love is the lighthouse guiding me through life's storms, and in your arms, I'm eternally warm.💖",
    "With you, every day is a gift, a treasure that my heart uplifts.💖",
    "In your eyes, I see the reflection of a love that's deep, a connection that I want to keep.💖",
    "Your love is the melody that plays in my heart's song, a love that's steady and forever strong.💖",
    "With every sunrise, I'm reminded of your radiant smile, and it warms my heart for miles.💖",
    "In the stillness of the night, I feel your love's sweet embrace, a comfort no one can replace.💖",
    "You are the melody that plays in my heart's song, a love that's steady and strong.💖",
    "With you, every day is a treasure trove of moments, and our love's journey is the ultimate compliment.💖",
    "In your eyes, I find the reflection of our shared dreams, a love story that forever gleams.💖",
    "Your love is the lighthouse guiding me through life's storms, keeping me safe, and my heart warms.💖",
    "Like a river flows gently to the sea, your love's current carries you to me.💖",
    "In the garden of our love, you are the most beautiful rose, and in your presence, my heart glows.💖",
    "With you, my heart is a symphony, a melodious song, a love that's forever strong.💖",
    "Your laughter is the sweetest note in life's grand melody, a source of endless harmony.💖",
    "In your smile, I see the dawn of a new day, a promise of love that's here to stay.💖",
    "Your love is the compass that guides me on life's quest, through every trial, you are the best.💖",
    "With you, every day is a canvas for our love's art, and it paints a masterpiece from the heart.💖",
    "In your embrace, I find the shelter from life's storm, a love that's pure and endlessly warm.💖",
    "Like a star in the night, your love lights my way, and I'm grateful for you every day.💖",
    "With you, every moment is a precious gem, a love that's pure, no need to condemn.💖",
    "Your laughter is the magic that brightens my days, and in your love, my heart sways.💖",
    "In your smile, I see the promise of a love so true, a future together, me and you.💖",
    "Your love is the anchor in life's turbulent sea, holding me steady, setting me free.💖",
    "With you, every day is an adventure, a journey that's boundless, where our love finds rapture.💖",
    "In your eyes, I see a universe, a world of dreams, where love endlessly streams.💖",
    "Your love is the poetry that dances in my soul, a story of us that makes me whole.💖",
    "With you, life is a grand masterpiece, a journey with love that will never cease.💖",
    "Your laughter is the sweetest symphony, a melody of love and endless harmony.💖",
    "In your smile, I find the key to my heart's delight, a love so strong, it feels just right.💖",
    "Your love is the lighthouse guiding me through life's storms, and in your arms, I'm eternally warm.💖",
    "With you, every day is a gift, a treasure that my heart uplifts.💖",
    "I cherish your love like a rare, precious gem, a treasure I'll always hold dear to the end.💖",
    "With you, every day feels like a magical dream, a love so beautiful, it makes my heart gleam.💖",
    "In your eyes, I see a love so pure and true, a connection between me and you that continually renews.💖",
    "Your love is the anchor that keeps me steady, a source of strength when life feels unsteady.💖",
    "Like the stars in the sky, your love shines bright, guiding me through the darkest night.💖",
    "With you, every day is a chance to explore, our love is a journey that leaves me wanting more.💖",
    "In your embrace, I find peace and warmth, a place where my heart takes comfortable refuge.💖",
    "Your laughter is a symphony, a sweet melody, the soundtrack of my heart's happiest story.💖",
    "In your smile, I find the light of a new day, a love that sweeps my doubts away.💖",
    "Your love is the compass that leads me on, even when the path is rough and long.💖",
    "With you, every moment feels like a treasure, a love that keeps growing without measure.💖",
    "In your eyes, I see the promise of our future, a love so strong it could never rupture.💖",
    "Your love is a beacon in life's darkest night, guiding me toward the warmth of your light.💖",
    "Like a river flows endlessly to the sea, your love flows to me, setting my heart free.💖",
    "With you, every day is a new beginning, a love story that keeps on spinning.💖",
    "In your embrace, I find my refuge, a sanctuary where my heart finds its usage.💖",
    "Your laughter is the music that fills my days, a joyful tune in so many ways.💖",
    "In your smile, I see the promise of a brighter day, a love that will never fade away.💖",
    "Your love is the anchor in life's rough sea, holding me steady, setting my heart free.💖",
    "With you, every day is a grand adventure, a love that grows and never loses its texture.💖",
    "In your eyes, I see a universe of love, where our hearts fit like a hand in a glove.💖",
    "Your love is the poetry my heart wants to hear, a story of us that's oh so clear.💖",
    "With you, life is a masterpiece, a canvas filled with love that will never cease.💖",
    "Your laughter is the sweetest serenade, in your love, my heart has found its crusade.💖",
    "In your smile, I see the promise of a love that's real, and my heart knows it's the ideal deal.💖",
    "Your love is the lighthouse that guides me home, in your arms, I'm never alone.💖",
    "With you, every day is a gift, a love that gives my spirits a lift.💖",
    "In your eyes, I find a reflection so clear, a love that is ever so near.💖",
    "Your love is a melody that plays in my heart, a symphony of love that sets me apart.💖",
    "With you, every moment becomes a memory, our love's story filled with endless glory.💖",
    "In your embrace, I find the warmth of your heart, a love that sets me apart.💖",
    "Your laughter is the sweetest music to my ears, a melody that banishes all fears.💖",
    "In your smile, I see the dawn of a brand-new day, a love that leads the way.💖",
    "Your love is the compass that guides me home, a journey that never leaves me alone.💖",
    "With you, every day is a journey of love, a story written high above.💖",
    "In your eyes, I see the stars in the night, a love that feels so right.💖",
    "Your love is a treasure, a gem so rare, a bond that we both hold with care.💖",
    "With you, every moment is a gift, a love that gives my spirits a lift.💖",
    "In your embrace, I find solace and grace, a love that no one can ever replace.💖",
    "Your laughter is a symphony, a joyful melody, a love that sets my heart free.💖",
    "In your smile, I find the sunshine of a new day, a love that will never fade away.💖",
    "Your love is the anchor that keeps me steady, in your arms, I'm forever ready.💖",
    "With you, every day is a grand adventure, a journey of love and endless rapture.💖",
    "In your eyes, I see a universe of love, a world where we fit like a hand in a glove.💖",
    "Your love is the poetry my heart wants to hear, a story of us that's oh so clear.💖",
    "With you, life is a masterpiece, a canvas filled with love that will never cease.💖",
    "Your laughter is the sweetest serenade, in your love, my heart has found its crusade.💖",
    "In your smile, I see the promise of a love that's real, and my heart knows it's the ideal deal.💖",
    "Your love is the lighthouse that guides me home, in your arms, I'm never alone.💖",
    "You are the light that guides me through the dark, The love that warms my heart and leaves its mark. In your eyes, I see a universe of dreams, And in your arms, I find my perfect team.💕",
    "Your love is a gentle breeze that kisses my soul, A warm embrace that makes me feel whole. In your eyes, I see my reflection, And in your heart, I find my protection.💕",
    "Love is a journey, and you are my guide, Together, we'll navigate life side by side. Your love is the compass that keeps me true, And in your arms, I find my happy place anew.💕",
    "You are the rhythm of my heart, The melody of my soul, The symphony of my life. In your love, I find my wholeness, My completeness, My forever.💕",
    "You are the sun that brightens my day, The moon that guides me through the night, And the stars that illuminate my dreams. In your love, I find my everything.💕",
    "I love you more than words can say, More than the stars in the night sky, More than the sand on the seashore. You are my everything, my heart, my soul.💕"
];

