const lovePoems = [
    "Roses are red, violets are blue, my love for you is endless and true.💖",
    "In your eyes, I see a universe of love, and in your embrace, I find my solace.💖",
    "Love is the journey of a lifetime, and I want to spend every moment of it with you.💖",
    "Your laughter is the sweetest music, and your love is the most precious gift.💖",
    "Like a gentle breeze, your touch soothes my soul and brings peace to my heart.💖",
    "In your smile, I find the courage to face each day, for it radiates warmth and hope.💖",
    "Your love is the canvas of my life, and together, we paint a masterpiece of passion.💖",
    "With you, every day is Valentine's Day, and every night, a dream of endless love.💖",
    "Your love is my anchor, grounding me in the stormy sea of life's uncertainties.💖",
    "In the tapestry of my life, you are the most beautiful thread, weaving love into my heart.💖",
    "You are the whisper of the wind, the glow of the moon, and the warmth of the sun in my life.💖",
    "I searched for love, and I found it in your eyes; now, I'm forever lost in your gaze.💖",
    "In your arms, I've found my sanctuary, where all worries fade, and love takes its place.💖",
    "Your love is a symphony that fills my heart with sweet melodies.💖",
    "Every moment with you is a treasure, a love story that I want to cherish forever.💖",
    "Your smile lights up the darkest corners of my soul, bringing warmth and joy.💖",
    "In your presence, I've discovered the magic of love, and it's a spell I never want to break.💖",
    "Love is not just a word; it's the feeling I get when I'm with you, so warm and real.💖",
    "With you, the ordinary becomes extraordinary, and life is a beautiful adventure.💖",
    "I fall in love with you every day, as your love is a gift that keeps on giving.💖",
    "You are the answer to all my questions, and in your love, I find my purpose.💖",
    "In your embrace, I've found my home, and in your heart, my eternal love.💖",
    "Our love is a journey with no end, filled with memories and dreams to share.💖",
    "Your love is a guiding star, leading me through life's uncharted territories.💖",
    "When we are apart, I feel incomplete, for you are the missing piece of my soul.💖",
    "Your love is a gentle rain, quenching the thirst of my heart's barren land.💖",
    "Like a river flows to the sea, your love always finds its way to me.💖",
    "In the garden of love, you are the most beautiful, radiant flower.💖",
    "Your love is a symphony that plays in the depths of my heart, sweet and harmonious.💖",
    "When I say 'I love you,' it's not out of habit; I say it to remind you that you are my life.💖",
    "In your eyes, I see a future where we share love, laughter, and endless adventures.💖",
    "Your love is the melody that lulls me to sleep and wakes me with a joyful heart.💖",
    "With you, every day is an opportunity to write a new chapter of our love story.💖",
    "I am yours, and you are mine; together, we create a love that is endlessly divine.💖",
    "Your love is a beacon of hope in the darkest night, guiding me to your warm embrace.💖",
    "In your laughter, I find happiness; in your love, I find my purpose.💖",
    "With you, my heart has found its home, a place where love and dreams intertwine.💖",
    "Your love is the treasure that I seek, and in your eyes, I find the universe I adore.💖",
    "Every day, I fall in love with you all over again, for your love is a beautiful renewal.💖",
    "You are the poetry of my heart, and every word is a testament to our love's art.💖",
    "In the canvas of my life, you are the most vibrant and beautiful stroke of love.💖",
    "With you, I've discovered the true meaning of love, and it's a story I want to keep telling.💖",
    "You are the sunshine that brightens my day, and the moonlight that comforts my night.💖",
    "Your love is the gentle rain that nurtures the garden of our hearts, making it bloom.💖",
    "In your eyes, I find a universe of love 💖",
    "In the melody of your laughter, my heart finds its song 💖",
    "In your smile, I see the morning sun's first ray,In your laughter, I find the joy of a brand new day. 💖",
    "Our love story is written in the stars, and I cherish every chapter as a gift from above.💕"

];

